#!/usr/bin/env python3
"""
setup_credentials.py — Interactive credential setup for code-creator / dbt-workflow.

Prompts for Jira, Databricks, and GitHub credentials and writes code-creator/.env.

Usage:
  python setup_credentials.py [--env-file PATH] [--yes]

pr-sheriff does not use this file and runs fully offline.
"""

from __future__ import annotations

import argparse
import getpass
import pathlib
import sys

FIELDS = [
    ("JIRA_BASE_URL", "Jira base URL (no trailing slash)", "https://moodysanalytics.atlassian.net", False),
    ("JIRA_EMAIL", "Jira account email", None, False),
    ("JIRA_API_TOKEN", "Jira API token", None, True),
    ("DATABRICKS_HOST", "Databricks workspace URL", None, False),
    ("DATABRICKS_HTTP_PATH", "Databricks SQL warehouse HTTP path", None, False),
    ("DATABRICKS_ACCESS_TOKEN", "Databricks personal access token", None, True),
    ("GITHUB_TOKEN", "GitHub token (Contents + Pull requests write)", None, True),
    ("GITHUB_REPO", "GitHub repo (org/repo)", "moodysanalytics/kyc-data-pipelines", False),
    ("GITHUB_BASE_BRANCH", "Base branch for feature branches", "dev", False),
]

HELP_LINKS = {
    "JIRA_API_TOKEN": "https://id.atlassian.com/manage-profile/security/api-tokens",
    "DATABRICKS_ACCESS_TOKEN": "Databricks UI → User Settings → Developer → Access tokens",
    "GITHUB_TOKEN": "https://github.com/settings/tokens",
}


def prompt_value(name: str, label: str, default: str | None, secret: bool) -> str:
    hint = ""
    if name in HELP_LINKS:
        hint = f"  ({HELP_LINKS[name]})"
    default_text = f" [{default}]" if default else ""
    while True:
        if secret:
            raw = getpass.getpass(f"{label}{default_text}{hint}: ")
        else:
            raw = input(f"{label}{default_text}{hint}: ")
        value = raw.strip() or (default or "")
        if value:
            return value
        print("  Value required — try again.")


def load_existing(path: pathlib.Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = val.strip()
    return values


def write_env(path: pathlib.Path, values: dict[str, str]) -> None:
    sections = [
        ("Jira", ["JIRA_BASE_URL", "JIRA_EMAIL", "JIRA_API_TOKEN"]),
        ("Databricks (dev workspace)", ["DATABRICKS_HOST", "DATABRICKS_HTTP_PATH", "DATABRICKS_ACCESS_TOKEN"]),
        ("GitHub", ["GITHUB_TOKEN", "GITHUB_REPO", "GITHUB_BASE_BRANCH"]),
    ]
    lines = [
        "# Generated by setup_credentials.py — used by code-creator and dbt-workflow.",
        "# pr-sheriff does not read this file.",
        "",
    ]
    for title, keys in sections:
        lines.append(f"# ─── {title} " + "─" * max(1, 60 - len(title)))
        for key in keys:
            val = values.get(key, "")
            lines.append(f"{key}={val}")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Interactive credential setup.")
    parser.add_argument(
        "--env-file",
        default=str(pathlib.Path(__file__).resolve().parent.parent / ".env"),
        help="Path to write .env (default: code-creator/.env)",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Write file without final confirmation prompt",
    )
    args = parser.parse_args()
    env_file = pathlib.Path(args.env_file)
    existing = load_existing(env_file)

    print("=== dbt Agent Skills — Credential Setup ===")
    print()
    print("Required for: code-creator, dbt-workflow")
    print("Not required for: pr-sheriff (offline validation only)")
    print()
    if existing:
        print(f"Existing values in {env_file} will be kept when you press Enter.")
    print()

    values: dict[str, str] = {}
    for name, label, default, secret in FIELDS:
        current = existing.get(name, default or "")
        if current and not secret:
            shown_default = current
        else:
            shown_default = default
        values[name] = prompt_value(name, label, shown_default, secret)

    print()
    print("Summary (secrets masked):")
    for name, _, _, secret in FIELDS:
        val = values[name]
        display = "***" if secret and val else val
        print(f"  {name}={display}")

    print()
    if not args.yes:
        confirm = input(f"Write credentials to {env_file}? [Y/n]: ").strip().lower()
        if confirm not in ("", "y", "yes"):
            print("Aborted — no file written.")
            sys.exit(0)

    env_file.parent.mkdir(parents=True, exist_ok=True)
    write_env(env_file, values)
    print(f"Wrote {env_file}")
    print()
    print("Next:")
    print(f"  python {env_file.parent / 'scripts' / 'check_setup.py'}")
    print("  Configure Databricks + Jira MCP in Cursor (see SETUP.md at repo root).")
    print("  Then run code-creator or dbt-workflow.")


if __name__ == "__main__":
    main()
